name: {{ cookiecutter.project_name }}
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.10.11
  - pip=22.0.4

  # PyTorch
  - pytorch=2.0.0
  - torchvision=0.15.0
  - pytorch-cuda=11.8

  # PyTorch Extras
  - lightning=2.0.2

  # Data Science
  - scikit-learn=1.2.2
  - pandas=1.5.3
  - seaborn=0.12.2

  # Jupyter
  - jupyter=1.0.0

  # MLFlow
  - mlflow=2.3.1
  - boto3=1.24.28

  - pip:
    # PyTorch Extras
    - jsonargparse[signatures]==4.21.1
    - tensorboard==2.13.0
    - rich==13.3.5
