name: {{ coockiecutter.project_name }}
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10.11
  - pytorch=2.0.0
  - pytorch-cuda=11.8
  - numpy=1.23.5
  - pandas=1.5.3
  - seaborn=0.12.2
  - jupyter=1.0.0
